name: Terraform Destroy Condicional

on:
  push:
    branches:
      - main

jobs:
  destroy:
    name: Terraform Destroy se destroy=true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar yq para ler YAML
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Verificar se destroy está ativado
        id: check_destroy
        run: |
          echo "DESTROY_FLAG=$(yq '.destroy' projeto.yml)" >> $GITHUB_ENV

      - name: Mostrar valor do destroy
        run: echo "Destroy está como: ${{ env.DESTROY_FLAG }}"

      - name: Configurar AWS Credentials
        if: env.DESTROY_FLAG == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: sa-east-1

      - name: Instalar Terraform
        if: env.DESTROY_FLAG == 'true'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        if: env.DESTROY_FLAG == 'true'
        run: terraform init

      - name: Executar Terraform Destroy
        if: env.DESTROY_FLAG == 'true'
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
