name: Deploy ECS com Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform Apply no ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar acesso ao secret (parcial, seguro)
        run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | cut -c1-4
  
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: sa-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        run: terraform init

      - name: Planejar mudanças
        run: terraform plan -var-file="terraform.tfvars"

      - name: Aplicar mudanças
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
